spring:
  application:
    name: community

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  h2:
    console:
      enabled: true

  jwt:
    key: ${JWT_KEY}
    access_exp_time: ${ACCESS_EXP}
    refresh_exp_time: ${REFRESH_EXP}

  session:
    session_exp_time: ${SESSION_EXP}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
    server:
      tomcat:
        max-swallow-size: 40MB

file:
  upload-dir: ${LOCAL_UPLOAD_DIR}
  image-base-url: ${IMAGE_BASE_URL}

security:
  notSecuredList:
    - method: POST
      path: /members
    - method: ALL
      path: /images/**
    - method: GET
      path: /members/nickname-validation
    - method: GET
      path: /members/email-validation
    - method: POST
      path: /auth
    - method: PATCH
      path: /auth